development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Striper_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Striper_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Striper_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *test